import fs from 'node:fs/promises'
import path from 'node:path'
import { fileURLToPath } from 'node:url'
import crypto from 'node:crypto'
import { parseArgs, promptForConfig } from './prompts.js'
import { copyTemplate, replaceInFile, pathExists } from './utils.js'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const TEMPLATE_DIR = path.resolve(__dirname, '../template')

function generateApiKey() {
  return `osk_${crypto.randomBytes(24).toString('hex')}`
}

function printSuccess(projectDir, config) {
  const relativeDir = path.relative(process.cwd(), projectDir) || '.'
  console.log('')
  console.log(`\u2713 Cloned Open Stellar template`)
  console.log(`\u2713 Created .env.local with WalletConnect project ID placeholder`)
  if (config.deployTarget === 'vercel') {
    console.log(`\u2713 Configured vercel.json with --webpack build flag`)
  }
  if (config.deployTarget === 'docker') {
    console.log(`\u2713 Added Dockerfile for container deployment`)
  }
  console.log(`\u2713 Generated API key for admin access`)
  console.log('')
  console.log(`\u2192 cd ${relativeDir} && npm install && npm run dev`)
  console.log('')
}

export async function run(argv = process.argv.slice(2)) {
  const { projectName, skipPrompts } = parseArgs(argv)

  if (!projectName) {
    console.error('Usage: npx create-open-stellar-app <project-directory>')
    process.exit(1)
  }

  const targetDir = path.resolve(process.cwd(), projectName)

  if (await pathExists(targetDir)) {
    const entries = await fs.readdir(targetDir)
    if (entries.length > 0) {
      throw new Error(`Directory "${projectName}" is not empty. Choose an empty directory.`)
    }
  }

  const config = await promptForConfig({ projectName, skipPrompts })
  const adminApiKey = generateApiKey()

  await copyTemplate(TEMPLATE_DIR, targetDir, {
    deployTarget: config.deployTarget,
  })

  const envLocal = [
    '# Generated by create-open-stellar-app',
    `NEXT_PUBLIC_NODE_NAME=${config.nodeName}`,
    `STELLAR_NETWORK=${config.network}`,
    'NEXT_PUBLIC_WALLETCONNECT_PROJECT_ID=your-walletconnect-project-id',
    `ADMIN_API_KEY=${adminApiKey}`,
    'NEXT_PUBLIC_APP_URL=http://localhost:3000',
    '',
  ].join('\n')

  await fs.writeFile(path.join(targetDir, '.env.local'), envLocal, 'utf8')

  const replacements = {
    '__PROJECT_NAME__': projectName,
    '__NODE_NAME__': config.nodeName,
    '__NETWORK__': config.network,
    '__DEPLOY_TARGET__': config.deployTarget,
    '__ADMIN_API_KEY__': adminApiKey,
  }

  for (const fileName of ['README.md', '.env.example', 'package.json']) {
    await replaceInFile(path.join(targetDir, fileName), replacements)
  }

  printSuccess(targetDir, config)
}
